# Generated by Django 4.2.26 on 2025-11-28 05:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/awards/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/certificates/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Цели', max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/licenses/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/reviews/')),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Стратегия', max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/strategy/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Задачи', max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'информацию о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='projectgallery',
            options={'ordering': ['order', '-completion_date'], 'verbose_name': 'проекты', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-featured', '-created_at'], 'verbose_name': 'отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='about_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='company_name',
            field=models.CharField(default='Наименование компании', max_length=200, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='happy_clients',
            field=models.PositiveIntegerField(default=50, verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='mission_statement',
            field=models.TextField(verbose_name='Миссия'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='projects_completed',
            field=models.PositiveIntegerField(default=100, verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tagline',
            field=models.CharField(default='Слоган', max_length=300, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='years_experience',
            field=models.PositiveIntegerField(default=10, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='projectgallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Font Awesome icon class', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
