# Generated by Django 4.2.26 on 2025-11-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutaward_aboutcertificate_aboutgoals_aboutlicense_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutaward',
            options={'verbose_name_plural': 'Награды'},
        ),
        migrations.AlterModelOptions(
            name='aboutcertificate',
            options={'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='aboutgoals',
            options={'verbose_name_plural': 'Цели'},
        ),
        migrations.AlterModelOptions(
            name='aboutlicense',
            options={'verbose_name_plural': 'Лицензии'},
        ),
        migrations.AlterModelOptions(
            name='aboutreview',
            options={'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='aboutstrategy',
            options={'verbose_name_plural': 'Стратегия'},
        ),
        migrations.AlterModelOptions(
            name='abouttasks',
            options={'verbose_name_plural': 'Задачи'},
        ),
    ]
