# Generated by Django 4.2.26 on 2025-11-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aboutaward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutlicense',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
