# Generated by Django 4.2.26 on 2025-12-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutlicense_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutReview',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=1, upload_to='about/reviews/'),
            preserve_default=False,
        ),
    ]
