# Generated by Django 4.2.26 on 2025-12-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_aboutreview_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='about/reviews/', verbose_name='Изображение'),
        ),
    ]
