# Generated by Django 4.2.26 on 2025-11-28 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Форма обратной связи'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='contact_type',
            field=models.CharField(choices=[('general', 'Общий запрос'), ('quote', 'Запросить цену'), ('consultation', 'Консультация'), ('support', 'Поддержка')], default='general', max_length=20, verbose_name='Вид обращения'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='responded',
            field=models.BooleanField(default=False, verbose_name='Отвечено'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='business_hours',
            field=models.TextField(default='Пн-Пт: 8:00-18:00, обед 12:00-14:00', verbose_name='Рабочие часы'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='company_name',
            field=models.CharField(default='Компания', max_length=200, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Экстренные контакты'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
